### ISSUE TITLE
[Anon] Kingdom of Bretonnia - Bretonnian Exiles: Les bretonniens ne paient pas les 25pts de GB

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#100]
**Problem:**
Les bretonniens ne paient pas les 25pts de GB

**Expected:**
Supprimer le cout des 25pts

**List:** https://www.newrecruit.eu/app/list/FcB49

**Comment by Tidomann** [comment]
The cost of 25 points for the BSB is for the war banner upgrade.
//
Le coût de 25 points pour de GB correspond à l'amélioration de la bannière de guerre.
