### ISSUE TITLE
[Anon] Orc and Goblin Tribes: Claims that you need a black orc mob to have black orc characters for the orcs & goblins grand army list

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#103]
**Problem:**
Claims that you need a black orc mob to have black orc characters for the orcs & goblins grand army list

**Expected:**
you can have 0-1 per 1000pts of black orc warboss, black orc bigboss can be taken freely

 **Additional Info:**
this info is found in the forces of evil book and is copied in the old world rules index https://tow.whfb.app/warhammer-armies/orc-and-goblin-tribes-army-list

**List:** https://www.newrecruit.eu/app/list/L427f

**Comment by Tidomann** [comment]
https://tow.whfb.app/special-rules/da-boyz

our army must include one Black Orc Boss for every Black Orc Mob it includes, and vice versa.
