### ISSUE TITLE
[Anon] Skaven: Skaven - Warlock Engineer and Plague Priest have no Magic Armour option.

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#104]
**Problem:**
Skaven - Warlock Engineer and Plague Priest have no Magic Armour option.

**Expected:**
If not paying to make them a wizard, they should have all Magic Armour available.

 **Additional Info:**
The option only opens up if made a wizard (with warpstone armour).

**List:** https://www.newrecruit.eu/app/list/pGT5S

**Comment by Tidomann** [comment]
Pg. 340
Only a model that is equipped with (or that has the option to be equipped with) armour, a shield or barding may purchase a magical equivalent. 

https://tow.whfb.app/magic-items/magic-armour
