### ISSUE TITLE
[Anon] Beastmen Brayherds: Missing Item

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#105]
**Problem:**
Missing Item

**Expected:**
Rune of the Beast Ascendant

 **Additional Info:**
Chaos Mutations; Beastmen Brayherds
Ravening Hordes, p. 111

**List:** https://www.newrecruit.eu/app/list/1vRAu
**Unit:** Wargor, id: 8e12-2852-993c-67dd

**Comment by OzMakka** [comment]
Rune of the Beast Ascendant is an available Chaos Mutation for Wargors and Beastlords
25 PTS
_The Beastman's horns have twisted into the semblance of a potent daemonic rune. This promise of ascendency to the ranks of Daemonhood fills its followers with courage._

Beastman Chieftains only. Unless this character is fleeing, friendly Bestigor, Gor and Ungor Herds gain a +1 modifier to their Leadership characteristic whilst within this character's Command range (to a maximum of 10).
