### ISSUE TITLE
[Anon] Dwarfen Mountain Holds: Having trouble with DMH in The Old World: Royal Clan being selected as the main force.

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#108]
**Problem:**
Having trouble with DMH in The Old World: Royal Clan being selected as the main force.

**Expected:**
When Royal Clan is selected the main force should become a Royal clan force. It looks like currently you select Royal Clan you have to add an allies list to get the list restrictions/benefits to show. Specifically the points in runes addition, specific units, BSB on the Runesmith/lord option.

**List:** https://www.newrecruit.eu/app/list/rPDD7

**Comment by Tidomann** [comment]
In the shared list- the force is still regular dwarfen mountain hold. I don't believe there is the ability to swap main forces- as each is it's own .cat entry. The force would have to be deleted and a new main force added.
