### ISSUE TITLE
[Anon] Orc and Goblin Tribes: Not available “Dead ‘Ard Armour” to equip characters.

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#110]
**Problem:**
Not available “Dead ‘Ard Armour” to equip characters.

**Expected:**
This option (35 pts) to be available

 **Additional Info:**
Arcane Journal: Orc & Goblin Tribes, p. 47

**Comment by Tidomann** [comment]
Tested- Require more information on what is failing
Works on Black Orc Bigboss on
- No Mount
- Orc Boar Chariot
- War Board
- Black Orc Chariot

Works on Black Orc Warboss on
- No Mount
- Orc Boar Chariot
- War Board
- Black Orc Chariot
Correctly Hidden on:
- Wyvern

Works on Orc Bigboss on
- No Mount
- Orc Boar Chariot
- War Board


Works on Orc Warboss on
- No Mount
- Orc Boar Chariot
- War Board
- Black Orc Chariot
Correctly Hidden on:
- Wyvern

Correctly Hidden on:
- Goblin characters
- Night Goblin characters
- Troll Hag
