### ISSUE TITLE
[Anon] Orc and Goblin Tribes - Troll Horde: When swapping units to new force

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#111]
**Problem:**
When swapping units to new force

**Expected:**
To retain general selected flag

 **Additional Info:**
General is still selected, however it thinks the association is linked to the prior force.. nothing changes this

**List:** https://www.newrecruit.eu/app/list/Rv18R

**Comment by Tidomann** [comment]
cant make sense of it
not sure what its meant with association
