### ISSUE TITLE
[Anon] Dwarfen Mountain Holds: no option to add runes

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#113]
**Problem:**
no option to add runes

**Expected:**
as with other dwarf machinery I was expecting to see the engineering runes tab

**List:** https://www.newrecruit.eu/app/list/uM3WZ
**Unit:** Organ Gun, id: 1257-bb2c-1a14-a356

**Comment by Tidomann** [comment]
Organ gun has no points for magic runes
