### ISSUE TITLE
[Anon] Chaos Dwarfs: Cost of Black Orc Command Models in Chaos Dwarf army is incorrect.

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#114]
**Problem:**
Cost of Black Orc Command Models in Chaos Dwarf army is incorrect.

**Expected:**
I excepted the boss, standard bearer and musician to cost 6 points each.

**List:** https://www.newrecruit.eu/app/list/MPQYj

**Comment by Tidomann** [comment]
Because of motley crew- the equipment of the standard bearer, champion, and musician have to be decided when list building. Adding any command adds an entire model + cost, as well as gives the option to customize all equipment.
