### ISSUE TITLE
[Anon] Lizardmen: in the list overview it tells me this list contains 1999 points worth of models. When I enter the list it tells me it only contains 1967 points worth of models.

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#115]
**Problem:**
in the list overview it tells me this list contains 1999 points worth of models. When I enter the list it tells me it only contains 1967 points worth of models.

**Expected:**
show the same amount of points every time.

**List:** https://www.newrecruit.eu/app/list/crY6q

**Comment by Tidomann** [comment]
May be from a points adjustment lagging update? Sent to New Recruit devs
