### ISSUE TITLE
[Anon] High Elf Realms: High Elf Noble should be allowed to take a Dragon Mount

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#116]
**Problem:**
High Elf Noble should be allowed to take a Dragon Mount

**Expected:**
Mount can only be selected with Blood of Caledor honor

**List:** https://www.newrecruit.eu/app/list/Hwsb7

**Comment by Tidomann** [comment]
Cannot take dragon mounts normally as per forces of fantasy pg 160
