### ISSUE TITLE
[Anon] Dark Elves: Blood Armour is not on the list

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#117]
**Problem:**
Blood Armour is not on the list

**Expected:**
Blood Armour available

 **Additional Info:**
https://www.newrecruit.eu/wiki/tow/warhammer-the-old-world/magic-items/3db3-9b83-edea-bbc9/blood-armour

**List:** https://www.newrecruit.eu/app/list/bP4mi
**Unit:** Dark Elf Dreadlord, id: 7ce3a1f2-13626bc

**Comment by Tidomann** [comment]
Make sure you are using the latest version of the rules. Blood armour is infantry and cavalry only in the Dark Elf pdf.
