### ISSUE TITLE
[Anon] Tomb Kings of Khemri: The "Skulls of the Foe" special rule is missing from the Screaming skull catapult special rules. Is listed in Ravening Hordes page 147.


### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#118]
**Problem:**
The "Skulls of the Foe" special rule is missing from the Screaming skull catapult special rules. Is listed in Ravening Hordes page 147.

**Expected:**
That all the special rules, including "Skulls of the Foe" would be listed when inspecting the screaming skull catapult.

**List:** https://www.newrecruit.eu/app/list/azsw5
**Unit:** Screaming Skull Catapult[2], id: c0cc-c64-62d3-53d1

**Comment by Tidomann** [comment]
The Skulls of the Foe is not missing from the screaming skull catapult. It is an upgrade that must be purchased for 20 points as indicated in Page 147.

Once you select the upgrade for 20 points, it will have the special rule
