### ISSUE TITLE
[Anon] Tomb Kings of Khemri: The "Armour of the Ages" magic armour is not listed as a magic armour option for characters who should be eligible for it.


### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#119]
**Problem:**
The "Armour of the Ages" magic armour is not listed as a magic armour option for characters who should be eligible for it.

**Expected:**
To have "Armour of the Ages" listed for characters who can take it (it being a suit of light armour, so for example Royal Heralds should be able to take it). It can be found in Ravening Horders page 151.

**Comment by Tidomann** [comment]
I cannot reproduce. There is no selection where armour of ages is unavailable for a "Royal Herald" character.

Test on
Royal Herald
Tomb Prince
Tomb King

Mortuary Priests cannot take it- as they cannot take armour normally- thus they cannot purchase a Light Armour Magic according to the Magic Armour Rules 

See Magic Armour Page 340
