### ISSUE TITLE
[Anon] Skaven: Doomwheel Rats Options

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#120]
**Problem:**
Doomwheel Rats Options

**Expected:**
TOW Skaven Doomwheel should just have 1 set of Rats automatically. You shouldn't be able to choose the number of rats, and it shouldn't default as 0.

**List:** https://www.newrecruit.eu/app/list/9v3wS
**Unit:** Doomwheel, id: dcec5d06-27377490

**Comment by Tidomann** [comment]
Fixed in v1.0.92
