### ISSUE TITLE
[Anon] Skaven: TOW Skaven Screaming Bell Ringing the bell 10-11 incorrect

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#121]
**Problem:**
TOW Skaven Screaming Bell Ringing the bell 10-11 incorrect

**Expected:**
It's just missing the end of the text - I believe it cuts off during Extra Attacks and only says EXTRA.

**List:** https://www.newrecruit.eu/app/list/sNsVE
**Unit:** Grey Seer, id: 787f7908-b1f62fb2

**Comment by Tidomann** [comment]
Fixed in v1.0.92
