### ISSUE TITLE
[Anon] Chaos Dwarfs: Black Orc Mob Command listed as 18 pts each

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#122]
**Problem:**
Black Orc Mob Command listed as 18 pts each

**Expected:**
Command should be 6 pts each

**List:** https://www.newrecruit.eu/app/list/tFB0d
**Unit:** Black Orc Mobs, id: 5f47-448e-3eb4-c3dc

**Comment by Tidomann** [comment]
Because of motley crew- you must indicate what equipment the command model is equipped. The cost adds an additional model and counts towards the unit count.

Will revisit when links allow for selection replacement
