### ISSUE TITLE
[Anon] High Elf Realms: When removing Handmaiden of the everqueen as general, Sisters of Avelorn core choice name changes into Longbeards

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#125]
**Problem:**
When removing Handmaiden of the everqueen as general, Sisters of Avelorn core choice name changes into Longbeards

**Expected:**
Stay as sisters of Avelorn with exclamation mark next to it

**List:** https://www.newrecruit.eu/app/list/3DReZ

**Comment by Tidomann** [comment]
Fixed in v1.0.92
