### ISSUE TITLE
[Anon] Orc and Goblin Tribes: Black orc command cost to many points

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#127]
**Problem:**
Black orc command cost to many points

**Expected:**
Lower the points 

 **Additional Info:**
Orc and goblin tribes

**List:** https://www.newrecruit.eu/app/list/3Wlrp

**Comment by Tidomann** [comment]
Because of motley crew- you must indicate what equipment the command model is equipped. The cost adds an additional model and counts towards the unit count.

Will revisit when links allow for selection replacement
