### ISSUE TITLE
[Anon] Orc and Goblin Tribes: Wollopa's One Hit Wonda from the O&G Magic Weapons is misspelled.

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#129]
**Problem:**
Wollopa's One Hit Wonda from the O&G Magic Weapons is misspelled.

**Expected:**
It is currently spelled Wonds

**List:** https://www.newrecruit.eu/app/list/KAwUc
**Unit:** Night Goblin Warboss, id: 5b92-be0-1dc6-efbf

**Comment by Tidomann** [comment]
fixed in [v1.0.95](https://github.com/vflam/Warhammer-The-Old-World/releases/tag/v1.0.95)
