### ISSUE TITLE
[Anon] The Empire of Man - City-State of Nuln: List is restricting me to 1 war wagon in 2000 point Nuln army. 

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#131]
**Problem:**
List is restricting me to 1 war wagon in 2000 point Nuln army. 

**Expected:**
It shouldn't be restricted beyond normal special restrictions 

 **Additional Info:**
Arcane Journal army composition Nuln

**List:** https://www.newrecruit.eu/app/list/eMKFy
**Unit:** War Wagon[2], id: 2418-64f6-8229-f2e1

**Comment by Tidomann** [comment]
Nuln accidentally linked to the model, instead of the unit. Should be corrected. Thanks
