### ISSUE TITLE
[Anon] Orc and Goblin Tribes: Black orc warboss not allowed in list without black orc mob


### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#132]
**Problem:**
Black orc warboss not allowed in list without black orc mob

**Expected:**
Should be allowed, nowhere in the rule book is this disallowed

 **Additional Info:**
Ravenign Hordes pg. 11

**List:** https://www.newrecruit.eu/app/list/eRMax

**Comment by Tidomann** [comment]
Please refer to Da Boyz special rule Ravening Hordes pg. 45
