### ISSUE TITLE
[Anon] The Empire of Man: On the empire knight units it says I can't have drilled and stubborn in both units and I totally can the book says "0-1 units per 1000 can have" not may choose one that means in 2000 points two "units may have" and they may take both options as it is not listed as "may take one of the following" which happens all the time in the rules it clearly states if you can have only one option and the rule for the knights does not say that 

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#133]
**Problem:**
On the empire knight units it says I can't have drilled and stubborn in both units and I totally can the book says "0-1 units per 1000 can have" not may choose one that means in 2000 points two "units may have" and they may take both options as it is not listed as "may take one of the following" which happens all the time in the rules it clearly states if you can have only one option and the rule for the knights does not say that 

**Expected:**
The error it shows for the list to be removed as it is not illegal 

 **Additional Info:**
Warhammer the old world forces of fantasy 

**List:** https://www.newrecruit.eu/app/list/EQRmP

**Comment by Tidomann** [comment]
fixed in v1.1.03
unit options currently set the same as dwarf and orc unit options until category functionality is fixed at force level
