### ISSUE TITLE
[Anon] Dark Elves: Dread halberd in weapons choices for Master

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#20]
**Problem:**
Dread halberd in weapons choices for Master

**Expected:**
Normal halberd

 **Additinal Info:**
Dark Elves rules soucrebook

**List:** https://www.newrecruit.eu/app/list/lBglf

**Comment by Tidomann** [comment]
fixed, thank-you for the report
