### ISSUE TITLE
[Anon] Skaven: Once I make my engineer a wizard I can’t access the magic items

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#21]
**Problem:**
Once I make my engineer a wizard I can’t access the magic items

**Expected:**
Please fix

 **Additinal Info:**
Once I make the model a wizard I can’t access magic item.

**Comment by Tidomann** [comment]
Might be a mobile UI issue? Making an engineer a wizard unlocks the arcane item options- and reveals a lore selection- causing magic items to shift down on the screen. working as intended on PC and android
![image](https://github.com/user-attachments/assets/cd1319f6-6fb2-40db-872a-2fa3f99b9860)
