### ISSUE TITLE
[Anon] Dwarfen Mountain Holds: Ally army size set as 25%

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#23]
**Problem:**
Ally army size set as 25%

**Expected:**
You can take up to 25%

 **Additinal Info:**
Give opportunity to set allies army limit

In this case i want to take limit 240pts and use only ~180

So i may take up to 120 points on characters, and must take at least 60 pts

**List:** https://www.newrecruit.eu/app/list/Yeixf

**Comment by Tidomann** [comment]
#91 will be handling revamp of allies system
