### ISSUE TITLE
[Anon] Wood Elf Realms: Wardancers have the motley crew rules that allows a split between hand weapon and throwing spears. When I give extra hand weapon it gives to all wardancers and does not allow a split.

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#24]
**Problem:**
Wardancers have the motley crew rules that allows a split between hand weapon and throwing spears. When I give extra hand weapon it gives to all wardancers and does not allow a split.

**Expected:**
Adjustment to allow a split

 **Additinal Info:**
Forces of fantasy page 131

**List:** https://www.newrecruit.eu/app/list/aPWMh

**Comment by Tidomann** [comment]
Motley crew requires you to create two separate groups of wardancers so they can be uniquely equipped. Once a seperate group is created the amount can be adjusted and equipment can be customized
![image](https://github.com/user-attachments/assets/2436015c-651c-44cd-bd87-c72ef32d53d6)
