### ISSUE TITLE
[Anon] Orc and Goblin Tribes: Incorrect cost on Backstabbers Blade in the Old World Orcs and Goblin Tribes list

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#28]
**Problem:**
Incorrect cost on Backstabbers Blade in the Old World Orcs and Goblin Tribes list

**Expected:**
Expected it to be 25 points, cost is showing as 30 points

 **Additional Info:**
Orc and Goblin Tribes arcane journal page 46

**List:** https://www.newrecruit.eu/app/list/ipKNs

**Comment by Tidomann** [comment]
Fixed, thank-you for the report
