### ISSUE TITLE
[Anon] Orc and Goblin Tribes: When selecting "Frenzy/Warpaint" option for Orc Boar Boy mob, an error appears saying that armour is required.  However, no armour is required given the Warpaint special rule.  Works fine for Orc boar boyz

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#29]
**Problem:**
When selecting "Frenzy/Warpaint" option for Orc Boar Boy mob, an error appears saying that armour is required.  However, no armour is required given the Warpaint special rule.  Works fine for Orc boar boyz

**Expected:**
No error message appearing

**List:** https://www.newrecruit.eu/app/list/ZDZyh

**Comment by Tidomann** [comment]
Unable to reproduce-
Unit entry states:
- Replace light armour with the Frenzy special rule

Therefore- if taking the frenzy rule, the unity cannot have light armour.

To have heavy armour:
- The entire unit may replace light armour with heavy armour....

Light armour cannot be replaced twice. If frenzy is taken, the unit cannot have an armour entry. I do not get an error if armour is not selected when frenzy is purchased.
![image](https://github.com/user-attachments/assets/deb0cc35-a30a-46c0-97e6-7b5d2a5da431)
