### ISSUE TITLE
[Anon] The Empire of Man: Empire State Troops cannot have neither the Drilled Special Rule nor the Magic Standard options

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#31]
**Problem:**
Empire State Troops cannot have neither the Drilled Special Rule nor the Magic Standard options

**Expected:**
Not to have the options mentioned

 **Additional Info:**
Only Veteran State Troops can have these options (Forces of Fantasy page 57)

**List:** https://www.newrecruit.eu/app/list/qbvbl

**Comment by Tidomann** [comment]
State troops already do not have a selection of drilled or magic standard, however state missile troops do (pg 58)
