### ISSUE TITLE
[Anon] Dwarfen Mountain Holds: I cant add a Magic banner

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#32]
**Problem:**
I cant add a Magic banner

**Expected:**
I did it

**List:** https://www.newrecruit.eu/app/list/TLGTx
**Unit:** Ironbreakers, id: `8a97-eb6f-a3e-3e5c`

**Comment by Tidomann** [comment]
Ironbreaker magical standard is restricted by points limit- and the Unit Options toggle must be selected to show drilled/magical standard runes
