### ISSUE TITLE
[Anon] Orc and Goblin Tribes: The unique for Orc and Goblin army is wrong. the list show that weh i take 1 big’un, i cant take skirmish. This is wrong they are independent on each other

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#33]
**Problem:**
The unique for Orc and Goblin army is wrong. the list show that weh i take 1 big’un, i cant take skirmish. This is wrong they are independent on each other

**Expected:**
Big’un option on orc and goblin is 1 unit per army
While skirmish is 1 unit per 1-1000 points

 **Additional Info:**
Ravenging hord

**List:** https://www.newrecruit.eu/app/list/VEVDV

**Comment by Tidomann** [comment]
Requires clarification from the FAQ- most talk I've had dictates that the options are not independant
