### ISSUE TITLE
[Anon] Vampire Counts: Unit upgrade options showing above the unit and when imported into Warhall the upgrade is not there

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#39]
**Problem:**
Unit upgrade options showing above the unit and when imported into Warhall the upgrade is not there

**Expected:**
Have unit upgrades for all units show beside the unit build.

 **Additional Info:**
Vampire Counts Skeleton Warrior upgraded with Thrusting Spears is a good example of this issue

**List:** https://www.newrecruit.eu/app/list/eLPVD

**Comment by Tidomann** [comment]
Thanks for the report,
Fixed in v1.0.63
