### ISSUE TITLE
[Anon] Ogre Kingdoms: Ogre Kingdom Tyrant, Bruiser, and Hunters are able to take multiple Big Names.

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#40]
**Problem:**
Ogre Kingdom Tyrant, Bruiser, and Hunters are able to take multiple Big Names.

**Expected:**
Each unit is only allowed to have a single Big Name, but there can be multiple of the same name per army.

**List:** https://www.newrecruit.eu/app/list/kQNRu

**Comment by Tidomann** [comment]
Fixed in next release
