### ISSUE TITLE
[Anon] Orc and Goblin Tribes: Black Ork Warboss and Black Orc Bigboss being 0/0 in 2000 point army.

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#41]
**Problem:**
Black Ork Warboss and Black Orc Bigboss being 0/0 in 2000 point army.

**Expected:**
Black Ork Warboss should be 1 per 1000 points or 0/2, Black Orc Bigboss has no limit.

**List:** https://www.newrecruit.eu/app/list/kbWdf

**Comment by Tidomann** [comment]
Da Boyz special rules restricts black orc character and black orc mobs to require at least 1 selection of each.

If you add 1 black orc character, and 1 black orc mob- the restriction will be correct.
