### ISSUE TITLE
[Anon] High Elf Realms: Hi. Two report data issue for High Elf Realms army (WTOW):
- Why if I use a Dragon Helm with an other Magic Armour (eg Armour of Caledor) it gives me an error? I think it's a mistake. The Dragon Helm rules say: "May be worn with other armour."
- The Great Eagles do not have Flaming Attacks. I think it's a mistake.

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#42]
**Problem:**
Hi. Two report data issue for High Elf Realms army (WTOW):
- Why if I use a Dragon Helm with an other Magic Armour (eg Armour of Caledor) it gives me an error? I think it's a mistake. The Dragon Helm rules say: "May be worn with other armour."
- The Great Eagles do not have Flaming Attacks. I think it's a mistake.

**Expected:**
I expect you to kindly correct these two errors. Thank you very much!

**List:** https://www.newrecruit.eu/app/list/WSUEM

**Comment by Tidomann** [comment]
Although Dragon Helm can be worn with other armour the magic item rule "Limitations and Uniqueness" on page 337 states: In addition, a model can only purchase one magic item from each category. This does not allow a character to purchase both the Dragon Helm and Armour of Caledor as they are both in the Magic Armour category.

**Comment by Tidomann** [comment]
Removed flaming attacks from great eagles
