### ISSUE TITLE
[Anon] Warriors of Chaos - Heralds of Darkness: Chaos Warrior units missing.

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#45]
**Problem:**
Chaos Warrior units missing.

**Expected:**
Chaos Warrior unit seem to be missing entirely from the r

**List:** https://www.newrecruit.eu/app/list/j6ozR

**Comment by Tidomann** [comment]
Chaos warriors are not on the muster list for Heralds of Darkness.
