### ISSUE TITLE
[Anon] Warriors of Chaos - Heralds of Darkness: Galrauch not counting as a character with the mark of tzeentch for list requirements. 

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#46]
**Problem:**
Galrauch not counting as a character with the mark of tzeentch for list requirements. 

**Expected:**
Number of characters with marks should match units with the same mark, galrauch should count as a character with a mark of tzeentch.

**List:** https://www.newrecruit.eu/app/list/o5syu

**Comment by Tidomann** [comment]
Thanks for the report. Fixed
