### ISSUE TITLE
[Anon] Orc and Goblin Tribes: It has put a cap on black orc mobs under the special catagory

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#47]
**Problem:**
It has put a cap on black orc mobs under the special catagory

**Expected:**
When looking at the army comp in the book, this is wrong, that cap is only on black orc mobs when taken as core

**List:** https://www.newrecruit.eu/app/list/Mh0jT

**Comment by Tidomann** [comment]
See special rule Da Boyz under The Forces of Evil Ravening Hordes pg. 45
