### ISSUE TITLE
[Anon] Vampire Counts: you can build a list of vampire counts with no wizard whilst the rulebook specifies that the general must be a wizard

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#48]
**Problem:**
you can build a list of vampire counts with no wizard whilst the rulebook specifies that the general must be a wizard

**Expected:**
if the general is no wizard, the list is not legal

**List:** https://www.newrecruit.eu/app/list/55kne

**Comment by Tidomann** [comment]
Fixed in latest release v1.0.61
Thanks for the report.
