### ISSUE TITLE
[Anon] Orc and Goblin Tribes: ogdruz swampdigga is listed as a "behemoth (character)"

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#49]
**Problem:**
ogdruz swampdigga is listed as a "behemoth (character)"

**Expected:**
change to "regular infantry (named character)"

 **Additional Info:**
orcs and goblins arcane journal pg35

**Comment by Tidomann** [comment]
Fixed in latest release v1.0.61
Thanks for the report.
