### ISSUE TITLE
[Anon] Skaven: Skaven chieftain can be general and BSB

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#50]
**Problem:**
Skaven chieftain can be general and BSB

**Expected:**
General cannot be bsb

 **Additional Info:**
https://tow.whfb.app/characters/the-battle-standard-bearer-model

**List:** https://www.newrecruit.eu/app/list/eAMED

**Comment by Tidomann** [comment]
Fixed in latest release v1.0.61
Thanks for the report.
