### ISSUE TITLE
[Anon] Kingdom of Bretonnia: No Sirienne's Locket as an option for the Bretonnian Duke

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#51]
**Problem:**
No Sirienne's Locket as an option for the Bretonnian Duke

**Expected:**
To be in the Talismans section

 **Additional Info:**
Page 105 of Forces of Fantasy (Bretonnia)

**List:** https://www.newrecruit.eu/app/list/e71Mt

**Comment by Tidomann** [comment]
A new recruit bug fix caused improperly logic'd constraints to fail.
Fixed in latest release v1.0.61
Thanks for the report.
