### ISSUE TITLE
[Anon] Kingdom of Bretonnia: Sirienne's Locket not showing as an option

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#52]
**Problem:**
Sirienne's Locket not showing as an option

**Expected:**
Option to select Siriennes Locket

 **Additional Info:**
Kingdom of Bretonnia

**List:** https://www.newrecruit.eu/app/list/4yEbK
**Unit:** Duke, id: 9c0e-74f0-2dcf-6958

**Comment by Tidomann** [comment]
A new recruit bug fix caused improperly logic'd constraints to fail.
Fixed in latest release v1.0.61
Thanks for the report.
