### ISSUE TITLE
[Anon] Kingdom of Bretonnia: Missing Sirienne's Locket as Talisman Option for Duke

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#53]
**Problem:**
Missing Sirienne's Locket as Talisman Option for Duke

**Expected:**
Sirienne's Locket as a Talisman option for a Duke

 **Additional Info:**
Recreating list from LGT which had Sirienne's Locket on Duke, but option not available here

**List:** https://www.newrecruit.eu/app/list/8bo55
**Unit:** Duke, id: 9c0e-74f0-2dcf-6958

**Comment by Tidomann** [comment]
A new recruit bug fix caused improperly logic'd constraints to fail.
Fixed in latest release v1.0.61
Thanks for the report.
