### ISSUE TITLE
[Anon] Vampire Counts: Stomp attacks are listed as D6

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#55]
**Problem:**
Stomp attacks are listed as D6

**Expected:**
D3

 **Additional Info:**
Vampire Count army book pg.22

**List:** https://www.newrecruit.eu/app/list/5zhj9
**Unit:** Vampire Count, id: 2524de59-e6f4a0af

**Comment by Tidomann** [comment]
Thanks for the report,
Fixed in v1.0.63
