### ISSUE TITLE
[Anon] Warriors of Chaos - Heralds of Darkness: Herald of Darkness Gigantic Spawn of Chaos Marks of Chaos not counting towards The Shadow Grows special rule

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#57]
**Problem:**
Herald of Darkness Gigantic Spawn of Chaos Marks of Chaos not counting towards The Shadow Grows special rule

**Expected:**
Allow Gigantic Spawn of Chaos Marks to be counted towards The Shadow Grows

**List:** https://www.newrecruit.eu/app/list/LaFaK

**Comment by Tidomann** [comment]
Heralds of Darkness do not have marks of chaos but their own bespoke rule Cursed by the gods
