### ISSUE TITLE
[Anon] Skaven: It seems to me that the “Weapon Teams” unit is missing from the Skaven list for The Old World

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#59]
**Problem:**
It seems to me that the “Weapon Teams” unit is missing from the Skaven list for The Old World

**Expected:**
I would have expected that unit to appear in the list, but I can’t locate it.

**Comment by Tidomann** [comment]
Weapon teams are not purchased as a unit as they do not appear in the muster list. They are purchased as upgrades to Stormvermin and Clanrats.
