### ISSUE TITLE
[Anon] Beastmen Brayherds: Old list not updating to new unit options

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#61]
**Problem:**
Old list not updating to new unit options

**Expected:**
When I load a Beastmen Brayherd list that was created a few months ago, I don't have the option to modify that list with the Greater Chaos Spawn. I've tried refreshing (it's in browser) and the new option doesn't appear.

**List:** https://www.newrecruit.eu/app/list/U7kWg

**Comment by Tidomann** [comment]
As the data gets updated- old lists may retain the old data to ensure it can still be viewed and updated. You most likely need to recreate the list for it to pull in the latest data.

**Comment by Tidomann** [comment]
Under list options -> List Configuration
![image](https://github.com/user-attachments/assets/d0ae662d-ca22-47f9-b6cf-62533d2148ea)
Change the book to latest version
