### ISSUE TITLE
[Anon] Beastmen Brayherds: Chaos mutations list is missing 4 options

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#62]
**Problem:**
Chaos mutations list is missing 4 options

**Expected:**
9 different mutations

 **Additional Info:**
Ravening hordes, beastmen, shaggoth entry + list of mutations few pages later

**List:** https://www.newrecruit.eu/app/list/tm0qS
**Unit:** Dragon Ogre Shaggoth, id: 28de-3a6e-da9e-6d98

**Comment by Tidomann** [comment]
- Crown of Horns is character only
- Pelt of Midnight is character only
- Rune of the Beast Ascendant is Beastman Cheiftains only
- Gnarled hide is 'infantry' only.

The dragon ogre shaggoth does not qualify for any of these mutations as it is a monstrous creature.
