### ISSUE TITLE
[Anon] Orc and Goblin Tribes: Orc Mob Cant get diffrent weapon for his Motley Crew Rule

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#63]
**Problem:**
Orc Mob Cant get diffrent weapon for his Motley Crew Rule

**Expected:**
Let chose how many of weapons i can take to unit

**Comment by Tidomann** [comment]
Orc mobs do not have the motley crew rule.

If it's a black orc mob, use the option to split off one to create a new group. This way you can fully individualize the black orc unit as per the motley crew rule.
![image](https://github.com/user-attachments/assets/0bc5c611-dcac-47a2-beba-b66e8b4ea642)
