### ISSUE TITLE
[Anon] Vampire Counts: I don't see an option to make the Strigoi Ghoul King the General

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#64]
**Problem:**
I don't see an option to make the Strigoi Ghoul King the General

**Expected:**
This leaves an error in the army build

 **Additional Info:**
Additionally, if that character is the general it should allow a 0-1 Terrorgheist to be take as a Special choice but since I can't select that General I'm not getting this option either.

**List:** https://www.newrecruit.eu/app/list/zTBOp
**Unit:** Strigoi Ghoul King, id: aba2369b-f537e829

**Comment by Tidomann** [comment]
in order to be the general you need to purchase a wizard level as per the "The Death Of A General" rule on page 4
