### ISSUE TITLE
[Anon] Beastmen Brayherds: Dragon Ogre Shaggoth unable to select Slug-skin

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#65]
**Problem:**
Dragon Ogre Shaggoth unable to select Slug-skin

**Expected:**
AFAIK nothing disqualifies him from taking slug-skin

 **Additional Info:**
p111, ravening hordes

**List:** https://www.newrecruit.eu/app/list/eEHRR

**Comment by Tidomann** [comment]
Fixed  for release v1.0.68
