### ISSUE TITLE
[Anon] Skaven: Warlock Engineer & Plague Priest cannot select Warpstone Armour

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#67]
**Problem:**
Warlock Engineer & Plague Priest cannot select Warpstone Armour

**Expected:**
Should be able to equip Warpstone Armour (magic Armour)

 **Additional Info:**
Skaven Pdf

**List:** https://www.newrecruit.eu/app/list/g9Z3M
**Unit:** Warlock Engineer, id: 82a454fa-ddf305e4

**Comment by Tidomann** [comment]
#68 closed as per issue 68
