### ISSUE TITLE
[Anon] Dark Elves: The repeated bolt thrower profile is incorrect. It’s missing keywords like multiple wounds and rapid fire.

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#69]
**Problem:**
The repeated bolt thrower profile is incorrect. It’s missing keywords like multiple wounds and rapid fire.

**Expected:**
Please correct the profile and keywords for the “repeater bolt thrower” per source below. 

 **Additional Info:**
Source: https://tow.whfb.app/war-machines/bolt-throwers

**List:** https://www.newrecruit.eu/app/list/icHRw
**Unit:** Reaper Bolt Thrower[1], id: f7d761d-fda3dbd3

**Comment by Tidomann** [comment]
Fixed for release v1.0.70
