### ISSUE TITLE
[Anon] Beastmen Brayherds: The Minotaur unit has option for motley crew. Unable to select how many of each weapon/ shield option 

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#72]
**Problem:**
The Minotaur unit has option for motley crew. Unable to select how many of each weapon/ shield option 

**Expected:**
Ability to select how many shields, great weapons or additional hand weapon you want to take in unit 

**List:** https://www.newrecruit.eu/app/list/UAPi6
**Unit:** Minotaur Herds, id: 1a26-aa70-1899-a39e

**Comment by Tidomann** [comment]
Press this button
it splits off a new group of models that can have a different loadout of weapons
![image](https://github.com/user-attachments/assets/65be68c5-4b26-473c-b6f4-3bf961107f86)
![image](https://github.com/user-attachments/assets/21490d10-c7bc-443e-918c-a554cd1e1ed6)
all the command are treated as their own model and can have their own loadout as well
