### ISSUE TITLE
[Anon] High Elf Realms: The app says I cannot take Great Eagles.

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#74]
**Problem:**
The app says I cannot take Great Eagles.

**Expected:**
To take Great Eagles.

**List:** https://www.newrecruit.eu/app/list/oHuyh

**Comment by Tidomann** [comment]
Great eagles are only available once the list reaches 1000 points as per the muster list on page 155 of the Forces of Good book
