### ISSUE TITLE
[Anon] Vampire Counts: Cannot increase unit size

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#76]
**Problem:**
Cannot increase unit size

**Expected:**
Ability to increase unit size

**List:** https://www.newrecruit.eu/app/list/ZqlPD
**Unit:** Grave Guard, id: 26a6-2f5a-d104-e6f1

**Comment by Tidomann** [comment]
Unable to reproduce. May be a UI issue on mobile
