### ISSUE TITLE
[Anon] Tomb Kings of Khemri: Allied contingents can currently only be exactly 500 points

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#79]
**Problem:**
Allied contingents can currently only be exactly 500 points

**Expected:**
You should be able to customize the amount of points in your allied contingent

 **Additional Info:**
Because all allied contingents default to 500 points, it allows some illegal builds. For example, if you take a grand army that is 1635 out of 2000 points and add a 500 point allied detachment, you can currently fill that allied detachment with 125 points of core and 240 points of characters. Even though that detachment should only be allowed to take 182 points of characters because it is in reality a 365 point detachment.

**List:** https://www.newrecruit.eu/app/list/irxuS

**Comment by Tidomann** [comment]
#91 will be handling revamp of allies system
