### ISSUE TITLE
[Anon] Warriors of Chaos - Wolves of the Sea: Drilled should cost 1 pts more on Huscarls

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#80]
**Problem:**
Drilled should cost 1 pts more on Huscarls

**Expected:**
Drilled costs 2 pts for each miniature

**List:** https://www.newrecruit.eu/app/list/hk2m7

**Comment by Tidomann** [comment]
Thanks for the report, fixed for v1.0.76
