### ISSUE TITLE
[Anon] Kingdom of Bretonnia: sirene locket on hero on royal pegasus

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#82]
**Problem:**
sirene locket on hero on royal pegasus

**Expected:**
it should be valid item to pick when mounted on royal pegasus

 **Additional Info:**

**List:** https://www.newrecruit.eu/app/list/LYKx9

**Comment by Tidomann** [comment]
Sirienne's locket can be taken on a hero who is on royal pegasus. Don't see error in list. Adding locket would go over the 100 point magic item limit on duke
