### ISSUE TITLE
[Anon] Dwarfen Mountain Holds: Standard Bearer cannot select a Master Rune of Hesitation

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#83]
**Problem:**
Standard Bearer cannot select a Master Rune of Hesitation

**Expected:**
Standard Bearer should have access to runes. 

**List:** https://www.newrecruit.eu/app/list/R503s
**Unit:** Irondrakes, id: df0-38c1-c4be-49c3

**Comment by Tidomann** [comment]
User must select the "Unit Options" selection to unlock drilled and magic standard runes
