### ISSUE TITLE
[Anon] Daemons of Chaos: Plague Drones of Nurgle say the MODEL has Armour Bane 2

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#84]
**Problem:**
Plague Drones of Nurgle say the MODEL has Armour Bane 2

**Expected:**
The pdf specifically states that only the Rot Fly mount gains this Armour Bane 2

 **Additional Info:**
Daemons of Chaos Legacy Army List pdf

**Comment by Tidomann** [comment]
Fixed in v1.0.78
