### ISSUE TITLE
[Anon] High Elf Realms: When blood of caledor is selected the unit must be mounted on either a Barded Elven Steed, a Sun Dragon, a Moon Dragon, or a Star Dragon.

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#85]
**Problem:**
When blood of caledor is selected the unit must be mounted on either a Barded Elven Steed, a Sun Dragon, a Moon Dragon, or a Star Dragon.

**Expected:**
A validation to include a mount when blood of caledor is selected

 **Additional Info:**
Forces of Fantasy, p. 180

**Comment by Tidomann** [comment]
Fixed in v1.0.78
