### ISSUE TITLE
[Anon] High Elf Realms: I think at there is a typo on ‘ore’ in 

Magic Resistance: The Casting roll of any enemy spell (including Bound Spells) that targets a unit that includes one ore more models with this special rule suffers a modifier, as shown in brackets after the name of this special rule (-X). 
Note that this special rule is not cumulative. If two or more models in a unit have this special rule, use the highest modifier.



### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#86]
**Problem:**
I think at there is a typo on ‘ore’ in 

Magic Resistance: The Casting roll of any enemy spell (including Bound Spells) that targets a unit that includes one ore more models with this special rule suffers a modifier, as shown in brackets after the name of this special rule (-X). 
Note that this special rule is not cumulative. If two or more models in a unit have this special rule, use the highest modifier.

**Expected:**
ore should be ot

**List:** https://www.newrecruit.eu/app/list/HGoJx
**Unit:** Archmage, id: f6a0-7cdd-e1fb-dc70

**Comment by Tidomann** [comment]
Fixed in v1.0.78
