### ISSUE TITLE
[Anon] High Elf Realms: I think that is a typo in Annulian Crystal: Once per Turn, upon successfully casting a spell, the bearer of the Annulian Crystal can choose to forget that sell and immediately generate another (not including signature spells) in the usual manner. 
Note that it is possible the Wizard might generate the spell they just forgot, or one forgotten in a previous Turn. Consider it fate.



### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#87]
**Problem:**
I think that is a typo in Annulian Crystal: Once per Turn, upon successfully casting a spell, the bearer of the Annulian Crystal can choose to forget that sell and immediately generate another (not including signature spells) in the usual manner. 
Note that it is possible the Wizard might generate the spell they just forgot, or one forgotten in a previous Turn. Consider it fate.

**Expected:**
can choose to forget that’spell’

**Comment by Tidomann** [comment]
Fixed in v1.0.78
