### ISSUE TITLE
[Anon] Kingdom of Bretonnia - Bretonnian Exiles: Bretonian Baron with Siriennes Locket gives error

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#88]
**Problem:**
Bretonian Baron with Siriennes Locket gives error

**Expected:**
Perfectly legal setup

 **Additional Info:**
On Royal Pegasus, all OK. Change mount to Hippogrypgh and sirriennes disappears from selection list

**List:** https://www.newrecruit.eu/app/list/le4eC
**Unit:** Baron[1], id: bead-cbe6-d3b1-8e5

**Comment by Tidomann** [comment]
Sirienne’s Locket states: Models whose troop type is ‘infantry’ or ‘cavalry’ only

A baron on a Hippogryph is no longer those troop types, as the character is riding a behemoth.
