### ISSUE TITLE
[Anon] Kingdom of Bretonnia - Errantry Crusade: Missing items

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#89]
**Problem:**
Missing items

**Expected:**
Magic iiem "Crusader's Clarion" to be added to errantry list and lance to be added to paladin in the Old World Breton List

 **Additional Info:**
https://tow.whfb.app/magic-item/crusaders-clarion

**List:** https://www.newrecruit.eu/app/list/NppO2

**Comment by Tidomann** [comment]
Crusader's Clarion is unavailable to the paladin unless the character is mounted on a bretonnian warhorse

From the item: "The Crusader’s Clarion may only be taken by a model in an Errantry Crusade Army of Infamy that is mounted on a Bretonnian Warhorse only. "
