### ISSUE TITLE
[Anon] High Elf Realms: There is a typo in Sea Guard: A character with the Sea Guardd Elven Honour: 
 
May only be mounted on a lothern Skycutter (but cannot choose any other mount Options).
 
May be equipped with a Warbow for no additional points. If so, they may not take any additional, non-magical weapons.
 
Gains the Naval Discipline and Rallying Cry Special Rules.



### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#90]
**Problem:**
There is a typo in Sea Guard: A character with the Sea Guardd Elven Honour: 
 
May only be mounted on a lothern Skycutter (but cannot choose any other mount Options).
 
May be equipped with a Warbow for no additional points. If so, they may not take any additional, non-magical weapons.
 
Gains the Naval Discipline and Rallying Cry Special Rules.

**Expected:**
A character with the sea ‘guard’ elven honour

 **Additional Info:**
Forces of Fantasy, p. 180

**Comment by Tidomann** [comment]
Fixed in v1.0.78
