### ISSUE TITLE
[Anon] Dwarfen Mountain Holds - Royal Clan: Adding Ungrim Ironfist to a Royal Clan dwarf list doesn't allow to take Slayers

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#92]
**Problem:**
Adding Ungrim Ironfist to a Royal Clan dwarf list doesn't allow to take Slayers

**Expected:**
Adding Ungrim should allow to take Daemon Slayers or Dragon Slayers as Characters, at most one unit of Slayers as Core, and at most 4 Doomseekers as Special choices.

 **Additional Info:**
Source for rules : Arcane Journal Dwarfen Mountain Holds p.37, rule "King of the Slayer Hold" of Ungrim Ironfist

**List:** https://www.newrecruit.eu/app/list/UAsDM

**Comment by Tidomann** [comment]
taking Ungrim Ironfist as your GENERAL

Select the general selection for ungrim and those options will appear
