### ISSUE TITLE
[Anon] Daemons of Chaos: chaotic icons should not be limited to the BSB as chaotic gifts have the same wording

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#93]
**Problem:**
chaotic icons should not be limited to the BSB as chaotic gifts have the same wording

**Expected:**
to allow the three chaotic icons be selectable to all standard bearers

 **Additional Info:**
Reading from the legacy Daemons of chaos all standard bearers refer to a daemonic icon, which are listed 5 times in pages 27-31. The Heralds don't limit you to only chaotic icons, nor is a regular prohibited to chaotic icons 

**List:** https://www.newrecruit.eu/app/list/dlRKe

**Comment by Tidomann** [comment]
They are selectable- they don't show up because they aren't within the points limit of for daemonic icons for the bloodletters
