### ISSUE TITLE
[Anon] High Elf Realms: Blood of Caledor is only adding 9pts

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#94]
**Problem:**
Blood of Caledor is only adding 9pts

**Expected:**
It should add 15pts

**List:** https://www.newrecruit.eu/app/list/N13qZ

**Comment by Tidomann** [comment]
Blood of caledor allows the purchase of full plate armour at no additional cost. Since the character already had full plate armour equipped- you are seeing a 6 point discount
