### ISSUE TITLE
[Anon] Dwarfen Mountain Holds: Goblin hewer says I can only have 1 per army.

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#95]
**Problem:**
Goblin hewer says I can only have 1 per army.

**Expected:**
Should be able to have 1 per 1000 points with a slayer character in my army

**List:** https://www.newrecruit.eu/app/list/Cahk0

**Comment by Tidomann** [comment]
fixed in v1.0.80
