### ISSUE TITLE
[Anon] The Empire of Man: I cant choose magic shields on My engineers, and would like to be able to do so.

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#97]
**Problem:**
I cant choose magic shields on My engineers, and would like to be able to do so.

**Expected:**
I expected all the alegable options for magical items. 

 **Additional Info:**
There should be no issue in the rules about giving engineers magical shields as an option.

**List:** https://www.newrecruit.eu/app/list/P9bNJ
**Unit:** Engineer[1], id: 4c2d-89b6-50e5-d697

**Comment by Tidomann** [comment]
Only a model that is equipped with (or that has the option to be equipped with) armour, a shield or barding may purchase a magical equivalent.
